---

all:
  vars:
    admin_user: "{{ lookup('env', 'USER') }}"
    admin_group: "{{ lookup('env', 'USER') }}"  # assumes group name matches username
    admin_home_dir: "{{ lookup('env', 'HOME') }}"
    container_root: "{{ lookup('env', 'HOME') }}/Documents/containers"

ungrouped:
  hosts:
    localhost:

