---

- name: Prometheus Node Exporter (OS metrics)
  hosts: all
  become: true
  gather_facts: false
  vars:
    prom_node_exporter_version: "1.7.0"

  tasks:

    - name: Set fact for node_exporter install
      ansible.builtin.set_fact:
        install_node_exporter: false

    - name: Create node_exporter user group
      ansible.builtin.group:
        name: node_exporter

    - name: Create node_exporter user account
      ansible.builtin.user:
        name: node_exporter
        group: node_exporter
        shell: /sbin/nologin
        create_home: false
        comment: Prometheus node exporter for performance metrics
        local: true
        password: '!!'
        expires: -1
        password_expire_max: -1
        state: present

    - name: Check if /usr/sbin/node_exporter exists
      ansible.builtin.stat:
        path: /usr/sbin/node_exporter
      register: stat_node_exporter
      ignore_errors: true

    - name: Set fact to install node_exporter if it does not exist
      ansible.builtin.set_fact:
        install_node_exporter: true
      when: not stat_node_exporter.stat.exists

    - name: Check version if it exists
      when: stat_node_exporter.stat.exists
      block:
        # agent, version v0.40.1 (branch: HEAD, revision: f222e2e08)
        - name: Run command to get version
          ansible.builtin.shell: |
            set -o pipefail
            /usr/sbin/node_exporter --version | head -n 1 | awk '{print $3}'
          changed_when: false
          args:
            executable: /bin/bash
          register: node_exporter_version_results

        - name: Current version
          ansible.builtin.debug:
            var: node_exporter_version_results.stdout

        - name: Desired version
          ansible.builtin.debug:
            var: prom_node_exporter_version

        - name: Update fact to install node_exporter if version does not match
          ansible.builtin.set_fact:
            install_node_exporter: true
          when: node_exporter_version_results.stdout != prom_node_exporter_version

    - name: Setup node_exporter if required
      when: install_node_exporter
      block:

        - name: Download Prometheus node exporter
          ansible.builtin.get_url:
            url: "https://github.com/prometheus/node_exporter/releases/download/v{{ prom_node_exporter_version }}/node_exporter-{{ prom_node_exporter_version }}.linux-amd64.tar.gz"
            dest: /tmp/node_exporter.tar.gz
            mode: '0750'
            owner: root
            group: root

        - name: Unpack node exporter
          ansible.builtin.shell: |
            #!/bin/bash
            set -e  # exit on failure
            cd /tmp
            tar -zxf node_exporter.tar.gz
            mv -f node_exporter-*/node_exporter /usr/sbin/node_exporter
            chmod 750 /usr/sbin/node_exporter
            chown node_exporter:daemon /usr/sbin/node_exporter
            # restorecon -R -v /usr/sbin/node_exporter  # For SELinux
            rm /tmp/node_exporter.tar.gz
          args:
            executable: /bin/bash
          changed_when: true
          notify:
            - Restart node_exporter

    - name: Ensure file permissions on /usr/sbin/node_exporter
      ansible.builtin.file:
        path: /usr/sbin/node_exporter
        owner: node_exporter
        group: daemon
        mode: '0750'

    - name: Copy /etc/systemd/system/node_exporter.service
      ansible.builtin.copy:
        content: |
          [Unit]
          Description=Node Exporter

          [Service]
          Restart=always
          User=node_exporter
          EnvironmentFile=/etc/sysconfig/node_exporter
          ExecStart=/usr/sbin/node_exporter $OPTIONS

          [Install]
          WantedBy=multi-user.target
        dest: /etc/systemd/system/node_exporter.service
        owner: root
        group: root
        mode: '0644'
      notify:
        - Restart node_exporter

    - name: Copy /etc/sysconfig/node_exporter
      ansible.builtin.copy:
        content: |
          OPTIONS="--collector.textfile.directory /var/lib/node_exporter/textfile_collector \
          --web.listen-address={{ prom_node_exporter_port }}"
        dest: /etc/sysconfig/node_exporter
        owner: node_exporter
        group: daemon
        mode: '0640'
      notify:
        - Restart node_exporter

    - name: Systemctl daemon-reload
      ansible.builtin.systemd:
        daemon_reload: true
      changed_when: false

    - name: Create /var/lib/node_exporter directory
      ansible.builtin.file:
        path: /var/lib/node_exporter
        state: directory
        owner: root
        group: root
        mode: '0750'

    - name: Create /var/lib/node_exporter/textfile_collector directory
      ansible.builtin.file:
        path: /var/lib/node_exporter/textfile_collector
        state: directory
        owner: node_exporter
        group: daemon
        mode: '0750'

    - name: Make sure node_exporter service is enabled and running
      ansible.builtin.systemd:
        state: started
        enabled: true
        name: node_exporter

    - name: Flush handlers
      ansible.builtin.meta: flush_handlers

  handlers:
    - name: Restart node_exporter
      ansible.builtin.systemd:
        name: node_exporter
        state: restarted
